# Generated by Django 4.0.2 on 2022-03-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamemechanic',
            options={'verbose_name': 'Игровая механика', 'verbose_name_plural': 'Игровые механики'},
        ),
        migrations.AddField(
            model_name='novel',
            name='video_url',
            field=models.URLField(default='', verbose_name='Ссылка на трейлер'),
            preserve_default=False,
        ),
    ]
