# Generated by Django 4.0.2 on 2022-04-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_gamemechanic_options_novel_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='CourseSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='Номер')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='Вес')),
                ('html_layout', models.TextField(verbose_name='Верстка')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.coursetheme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
