# Generated by Django 4.0.2 on 2022-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_coursetheme_courseslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslide',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер'),
        ),
    ]
