# Generated by Django 4.0.2 on 2022-04-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_courseslide_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы задания',
            },
        ),
        migrations.AddField(
            model_name='coursetheme',
            name='has_practice',
            field=models.BooleanField(default=False, verbose_name='Наличие тестов'),
        ),
        migrations.CreateModel(
            name='TaskSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.coursetheme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('code', models.PositiveSmallIntegerField(default=0, verbose_name='Идентификатор по темам')),
                ('task_text', models.TextField(verbose_name='Текст задания')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='Вес')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.coursetheme', verbose_name='Тема')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.questiontype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('help_text', models.TextField(null=True, verbose_name='Подсказка')),
                ('error_text', models.TextField(null=True, verbose_name='Замечание при ошибке')),
                ('correct_text', models.TextField(null=True, verbose_name='Пояснение при верном ответе')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.taskquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
