# Generated by Django 4.0.2 on 2022-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_questiontype_coursetheme_has_practice_taskslide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslide',
            name='is_practice',
            field=models.BooleanField(default=False, verbose_name='Практика'),
        ),
    ]
