# Generated by Django 4.0.2 on 2022-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_courseslide_is_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskquestion',
            name='code',
            field=models.CharField(max_length=32, verbose_name='Идентификатор по темам'),
        ),
    ]
