# Generated by Django 4.0.2 on 2022-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_alter_taskquestion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='description',
            field=models.TextField(default='Новый тип', verbose_name='Описание'),
        ),
    ]
