# Generated by Django 4.0.2 on 2022-04-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_questiontype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskquestion',
            name='theme',
        ),
        migrations.AddField(
            model_name='taskquestion',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.taskslide', verbose_name='Тест'),
        ),
    ]
