# Generated by Django 4.0.2 on 2022-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_remove_taskquestion_theme_taskquestion_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanswer',
            name='help_text',
        ),
        migrations.AddField(
            model_name='taskquestion',
            name='help_text',
            field=models.TextField(null=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='taskquestion',
            name='task_header',
            field=models.CharField(default='Текст по умолчанию', max_length=150, verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='taskquestion',
            name='task_text',
            field=models.TextField(null=True, verbose_name='Расширенный текст'),
        ),
    ]
