# Generated by Django 4.0.2 on 2022-04-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_remove_taskanswer_help_text_taskquestion_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='correct_text',
            field=models.TextField(blank=True, verbose_name='Пояснение при верном ответе'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='error_text',
            field=models.TextField(blank=True, verbose_name='Замечание при ошибке'),
        ),
        migrations.AlterField(
            model_name='taskquestion',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='taskquestion',
            name='task_text',
            field=models.TextField(blank=True, verbose_name='Расширенный текст'),
        ),
    ]
