# Generated by Django 4.0.2 on 2022-04-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_taskblock_alter_taskquestion_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskquestion',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.taskslide', verbose_name='Тест'),
        ),
        migrations.DeleteModel(
            name='TaskBlock',
        ),
    ]
