# Generated by Django 4.0.2 on 2022-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0014_taskblock_alter_taskquestion_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskslide',
            options={'verbose_name': 'Слайд с тестом', 'verbose_name_plural': 'Слайды с тестами'},
        ),
        migrations.AddField(
            model_name='taskquestion',
            name='is_auto_check',
            field=models.BooleanField(default=False, verbose_name='Скрипт для проверки'),
        ),
    ]
