# Generated by Django 4.0.2 on 2022-04-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0015_alter_taskslide_options_taskquestion_is_auto_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskblock',
            name='url',
            field=models.URLField(null=True, verbose_name='Адрес блока'),
        ),
    ]
