# Generated by Django 4.0.2 on 2022-04-27 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0018_alter_taskblock_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_slides', models.ManyToManyField(related_name='read_slides', to='novels.CourseSlide', verbose_name='Прочитанные лекции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код вопроса')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно')),
                ('answers', models.ManyToManyField(related_name='user_answers', to='novels.TaskAnswer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
