# Generated by Django 4.0.2 on 2022-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0020_alter_useranswer_user_alter_userslides_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userslides',
            options={'verbose_name': 'Прочитанные слайды', 'verbose_name_plural': 'Прочитанные слайды'},
        ),
        migrations.AlterField(
            model_name='userslides',
            name='read_slides',
            field=models.ManyToManyField(null=True, related_name='read_slides', to='novels.CourseSlide', verbose_name='Прочитанные лекции'),
        ),
    ]
