# Generated by Django 4.0.2 on 2022-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0021_alter_useranswer_options_alter_userslides_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslides',
            name='read_slides',
            field=models.ManyToManyField(blank=True, related_name='read_slides', to='novels.CourseSlide', verbose_name='Прочитанные лекции'),
        ),
    ]
