# Generated by Django 4.0.2 on 2022-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0023_remove_useranswer_code_useranswer_id_quest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='id_quest',
            field=models.SmallIntegerField(default=0, verbose_name='Вопрос'),
        ),
    ]
