# Generated by Django 4.0.2 on 2022-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0024_alter_useranswer_id_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answers',
            field=models.JSONField(null=True),
        ),
    ]
