# Generated by Django 4.0.2 on 2022-04-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0027_remove_useranswer_user_useranswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='id_quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.taskquestion', verbose_name='Вопрос'),
        ),
    ]
