# Generated by Django 4.0.2 on 2022-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0028_alter_useranswer_id_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_textvalue',
            field=models.BooleanField(default=False, verbose_name='Ввод текста'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quest_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Код вопроса'),
        ),
    ]
