# Generated by Django 4.0.2 on 2022-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0030_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_cleared',
            field=models.BooleanField(default=False, verbose_name='Очищено'),
        ),
    ]
