# Generated by Django 4.0.2 on 2022-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0031_useranswer_is_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='auto_tests',
            field=models.TextField(default='', verbose_name='Автотесты'),
        ),
    ]
