# Generated by Django 4.0.2 on 2022-05-01 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0032_useranswer_auto_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_tests', models.ManyToManyField(blank=True, related_name='done_tests', to='novels.TaskSlide', verbose_name='Сделанные тесты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_slides', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Страницы тестов',
                'verbose_name_plural': 'Страницы тестов',
            },
        ),
    ]
