# Generated by Django 4.0.2 on 2022-05-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0034_remove_taskanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.taskquestion', verbose_name='Вопрос'),
        ),
    ]
